[package]
name = "advent-of-code"
version = "0.0.1"
description = "my solutions of advent of code"
authors = ["you"]
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
ureq = { version = "3.1.4", features = ["cookies"] }
